### ISSUE TITLE
account command in console do not return amount of Rnode reward

### ISSUE THREAD

**Issue by atmo4th** [CPChain/chain#42]
**Where does the bug occur?**
console

When i type in
`./console account`
the result i got is
```
--------------------------

Balance: xxx CPC

Reward:
        Total:  0 CPC
        Free:   0 CPC
        Locked: 0 CPC

--------------------------
```
Where xxx CPC is the amount of staked cpc minus 200k cpc contract plus the reward that i got from being Rnode. However i cant see how much i've earned in the reward section as it shows 0 CPC.

 - OS: Ubuntu 19.04
 - CPChain version 0.2.8
